import "./globals.css";
import { avenir, montserrat } from "./fonts.js";

export const metadata = {
  title: "Golden",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${avenir.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
